name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.239.128.197 >> ~/.ssh/known_hosts
          ssh-keyscan -H 44.202.154.238 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.208.53.19 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.211.195.173 >> ~/.ssh/known_hosts
          ssh-keyscan -H 3.86.147.16 >> ~/.ssh/known_hosts

      # Paso 3: Desplegar los archivos a cada instancia EC2
      - name: Deploy to EC2 instances
        run: |
          for IP in 34.239.128.197 44.202.154.238 54.208.53.19 54.211.195.173 3.86.147.16; do
            ssh -o StrictHostKeyChecking=no ec2-user@$IP <<EOF
              if [ ! -d "/home/ec2-user/Javascript-AWS" ]; then
                git clone https://github.com/mateocarruce/Javascript-AWS.git
              fi
              cd /home/ec2-user/Javascript-AWS
              git pull origin main  # Actualizar los archivos del repositorio
              sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
              sudo systemctl restart nginx  # Reiniciar Nginx
              EOF
          done
